[package]
# Package Information
name = oposs_huawei_ups
title = OPOSS Huawei UPS
author = Tobias Oetiker <tobi@oetiker.ch>
description = This check monitors Huawei UPS2000 systems via SNMP.

    It tracks alarms, power supply status, battery state, environmental
    conditions, three-phase input/output electrical parameters, and
    battery health metrics.

# CheckMK Compatibility
version.min_required = 2.3.0p1
version.packaged = 2.3.0p34

# Optional
download_url = https://github.com/oposs/cmk-oposs_huawei_ups
version.usable_until =

# Build Options
validate_python = true
